### PR TITLE
cgo is unsafe

### PR DESCRIPTION
**Pull request by josharian**

### CODE REVIEW

**Comment by josharian** [comment]
I can also see giving cgo its own symbol alongside the unsafe bomb, instead of making the bomb ambiguous. Opinions?

**Comment by bradfitz** [comment]
I'm fine either way.

I considered it too but was lazy at the time so omitted it, figuring most C code necessarily used unsafe anyway and would get picked up with a bomb that way.

**Comment by bradfitz** [comment]
In any case, LGTM

**Comment by josharian** [comment]
I can't think of a good emoji for C. My initial reaction was 🐍 because it can bite you, but that seemed too much like python. So whatever. I'll merge this and if anyone cares we can distinguish the two later.

**Pull request merged**
